(package "jayces-mode"
         "0.0.2"
         "Major mode for editing JayCeS file")

(website-url "https://github.com/jayces-lang/jayces-mode")
(keywords "lisp" "jayces")

(package-file "jayces-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
